### ISSUE TITLE
Cannot save/resign apk file

### ISSUE THREAD

**Issue by veso266** [kefir500/apk-editor-studio#100]
Hello there, thanks for a great program

For hours I am trying to change minSDK version of the following app: https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-camera/samsung-camera-11-0-16-6-release/samsung-camera-11-0-16-6-android-apk-download/

First, your app is the onlyone that properly shows the icon and parses the apk

But whenever I tried to change minSDK version and package name (I am trying to install this on Android 10, so minSDK must be 29), and so I don't need to break my existing camera app while I am playing I want to change package name from com.sec.android.app.camera to com.sec.android.app.camera2

When I try to save/sign this I get this error
W: J:\Decompile Stuff\Android\Tools\Modify Apps properties\apk-editor-studio_windows_1.7.0\APK Editor Studio v1.7.0\data\temp\apk\{7efdc134-dbba-47fe-bee6-2afb6badcd89}\res\values\dimens.xml:732: error: resource android:dimen/notification_header_height is private.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mitja\AppData\Local\Temp\brut_util_Jar_75026553946059850855914763504347535721.tmp, link, -o, C:\Users\Mitja\AppData\Local\Temp\APKTOOL5700249702542370009.tmp, --package-id, 127, --min-sdk-version, 29, --target-sdk-version, 30, --version-code, 1101606100, --version-name, 11.0.16.6, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\Mitja\AppData\Local\Temp\APKTOOL5340657368189179924.tmp, -0, arsc, -I, J:\Decompile Stuff\Android\Tools\Modify Apps properties\apk-editor-studio_windows_1.7.0\APK Editor Studio v1.7.0\data\frameworks\1.apk, --manifest, J:\Decompile Stuff\Android\Tools\Modify Apps properties\apk-editor-studio_windows_1.7.0\APK Editor Studio v1.7.0\data\temp\apk\{7efdc134-dbba-47fe-bee6-2afb6badcd89}\AndroidManifest.xml, J:\Decompile Stuff\Android\Tools\Modify Apps properties\apk-editor-studio_windows_1.7.0\APK Editor Studio v1.7.0\data\temp\apk\{7efdc134-dbba-47fe-bee6-2afb6badcd89}\build\resources.zip]

I mean, not sure maybe this app is corupted somehow, because it doesn't even recognize it in my Adnroid 10 phone

Thanks for Anwsering and Best Regards

**Comment by Ibuprophen** [comment]
These stock apps can be very difficult to modify certain things like the package name and such. This requires much more work (that's if it could be done).

The API/SDK levels may be as simple as just making sure that the following entries match with what your looking for... 

`android:minSdkVersion="integer"`
`android:targetSdkVersion="integer"`
`android:maxSdkVersion="integer"`

I hope I had explained this okay via text... :-)) 

~Ibuprophen

**Comment by veso266** [comment]
hmm, for some reason I was able to modify this version (for Adnroid 10) fine: https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-camera/samsung-camera-10-5-02-11-release/samsung-camera-10-5-02-11-android-apk-download/

Not sure why the updated version is giving me trouble

Although yea, at least samsung apps are extremly hard to update (it just tells you installed failed, and then you go figure out why)

I even tried to force update it by renaming apk to base.apk and copying it into /data/app/com.sec.android.camera.blahblah

and then the app just crashed on me 

The thing is that my Samsung Camera does not have Pro video mode, after almost enabling it via camera-feature.xml
but although the thing is enabled, it still lacks buttons I saw in youtube videos, like this: https://www.youtube.com/watch?v=KuKA8ODpw0Y

So then I thought, hmm, maybe my camera app is too old and does not support those buttons, thats why I am trying to update the app itself

Of course I don't want to update the whole android just because of a stupid camera :smile:

**Comment by kefir500** [comment]
Hi @veso266,

> When I try to save/sign this I get this error

This error is generated by Apktool which is used under the hood. According to this [issue](https://github.com/iBotPeaches/Apktool/issues/810), the problem can be fixed by replacing the faulty line `@android:dimen/notification_header_height` with `@*android:dimen/notification_header_height` (note the extra asterisk).

For this, you can use the global search & replace feature (`Ctrl+Shift+F`) or manually locate the `res/values/dimens.xml` file in the File System tab at the bottom left dock.

I'm not sure if the APK will install/run properly after this change, however, the APK now can be saved at least.

> But whenever I tried to change minSDK version

Lowering the minimum SDK value can lead to runtime crashes, e.g. when features from a new API are not supported on the target device.

**Comment by kefir500** [comment]
Closing the (Apktool-related) issue since there is a solution.
Feel free to reopen if you still have questions.
