### ISSUE TITLE
Separate idsig file being saved

### ISSUE THREAD

**Issue by MrSpoonie** [kefir500/apk-editor-studio#104]
When I save an APK it is now saving a separate idsig file.

**Comment by kefir500** [comment]
This is a signature file generated by the modern (Android 11+) APK Signature Scheme v4. You can read more about it [here](https://developer.android.com/about/versions/11/features#signature-scheme-v4).

**Comment by MrSpoonie** [comment]
Thank you
Now I feel stupid 😂

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by kefir500** [comment]
No problem, I just recently found out myself about the APK Signature Scheme v4 :)
