### ISSUE TITLE
i have a error while trying to pack an apk

### ISSUE THREAD

**Issue by LIBBYXDPG3D** [kefir500/apk-editor-studio#105]
so im trying to pack a apk called pvz 2 it says "packing apk", then it says later "error packing apk", i check to see what happened i cant tell is there any way someone tell me why cant i pack this apk?
also heres the log

I: Using Apktool 2.7.0
I: Copying C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412} classes.dex file...
I: Copying C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412} classes2.dex file...
I: Copying C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412} classes3.dex file...
I: Copying C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412} classes4.dex file...
I: Copying C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412} classes5.dex file...
I: Building resources...
W: C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412}\res\values\strings.xml:48: error: unescaped apostrophe in string
W: "PvZ 2 Libby's Revenge Test".
W: C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412}\res\values\strings.xml:48: error: not a valid string.
W: C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412}\res\values\strings.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Libby\AppData\Local\Temp\brut_util_Jar_27485935518483993561611378473981767532.tmp, compile, --dir, C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412}\res, --legacy, -o, C:\Users\Libby\AppData\Local\Temp\apk-editor-studio\apk\{d08206fb-04f8-469e-945e-1a7008234412}\build\resources.zip]

**Comment by LIBBYXDPG3D** [comment]
also ive been trying to figure this out for 1 week now.

**Comment by kefir500** [comment]
Hi @LIBBYXDPG3D,

According to this error message:
> error: unescaped apostrophe in string

Apostrophe characters must be escaped with a`\` character. So in the `res/values/strings.xml` resource file you should replace `PvZ 2 Libby's Revenge Test` with `PvZ 2 Libby\'s Revenge Test`.
