### ISSUE TITLE
Error trying to pack an APK

### ISSUE THREAD

**Issue by amiamiginal** [kefir500/apk-editor-studio#107]
I: Using Apktool 2.7.0
I: Copying C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b} classes.dex file...
I: Copying C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b} classes2.dex file...
I: Copying C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b} classes3.dex file...
I: Building resources...
W: C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b}\AndroidManifest.xml:20: error: unexpected element <supports-screens> found in <manifest><application>.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\slygi\AppData\Local\Temp\brut_util_Jar_77407235086757729553653510933014461554.tmp, link, -o, C:\Users\slygi\AppData\Local\Temp\APKTOOL2254607060755092788.tmp, --package-id, 127, --min-sdk-version, 3, --target-sdk-version, 8, --version-code, 10000, --version-name, 40.10, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --enable-sparse-encoding, -e, C:\Users\slygi\AppData\Local\Temp\APKTOOL5345226618120700727.tmp, -0, arsc, -I, C:\Users\slygi\AppData\Local\apk-editor-studio\frameworks\1.apk, --manifest, C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b}\AndroidManifest.xml, C:\Users\slygi\AppData\Local\Temp\apk-editor-studio\apk\{d37112a5-6453-4cc4-8941-2aaf9699573b}\build\resources.zip]

**Comment by kefir500** [comment]
This error is generated by the Apktool, which is used by APK Editor Studio under the hood for packing APK files. As stated in the message, you should check the line 20 in `AndroidManifest.xml` for errors. You can also post the `AndroidManifest.xml` file contents here.
