### ISSUE TITLE
There seems to be no decompilation of APK's DeX resources.

### ISSUE THREAD

**Issue by SONGjiemo** [kefir500/apk-editor-studio#110]
There seems to be no decompilation of APK's DeX resources.

**Comment by kefir500** [comment]
`dex` should be decompiled to `smali`.
Did you enable the `Decompile Source Code` checkbox in `Settings → Options → Apktool`?

**Comment by SONGjiemo** [comment]
> `dex` should be decompiled to `smali`. Did you enable the `Decompile Source Code` checkbox in `Settings → Options → Apktool`?

Thank you very much for your answer, but I found that search is not a global search function in the query resources. 
Is the search to support the entire file APK resources to search. 
This is very necessary. I hope to have this function.

**Comment by kefir500** [comment]
Sorry, I'm not sure I understand your request clearly.
Do you mean searching across file **names** or file **contents**?
- Searching by file **contents** is available under the `Tools` → `Search in Project` (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>).
- Searching by file **name** is currently available for the parsed resources, not the source code. I'll add the global search by file name in the upcoming APK Editor Studio v1.8.0. You can track the progress [here](https://github.com/kefir500/apk-editor-studio/issues/111). For now, you can open the required files manually under the `File System` tab.
