### ISSUE TITLE
Pack Apk File Error

### ISSUE THREAD

**Issue by ikpop** [kefir500/apk-editor-studio#114]
i dont know why if i rebuild apk and show this log
I: Building resources...
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:728: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:735: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:742: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:749: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:756: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:763: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:770: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:777: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:784: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:791: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:798: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:805: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:812: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:819: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:826: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:833: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:840: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:847: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:854: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
W: C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml:861: error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mgunr\AppData\Local\Temp\brut_util_Jar_74255992969222830804411450572292775836.tmp, link, -o, C:\Users\mgunr\AppData\Local\Temp\APKTOOL3208201695403651088.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 29, --version-code, 999999999, --version-name, 2.23.1.76, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\mgunr\AppData\Local\Temp\APKTOOL4707869524806446155.tmp, -0, arsc, -I, C:\Users\mgunr\AppData\Local\apk-editor-studio\frameworks\1.apk, --manifest, C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\AndroidManifest.xml, C:\Users\mgunr\AppData\Local\Temp\apk-editor-studio\apk\{c8505107-8894-4b93-916a-eb32208ab1a1}\build\resources.zip]

**Comment by Senliast** [comment]
+1

**Comment by kefir500** [comment]
Check out #121.
