### ISSUE TITLE
Not run mac os 11.3

### ISSUE THREAD

**Issue by maichanchinh** [kefir500/apk-editor-studio#115]
You have macOS 11.3.1. The application requires macOS 12.6 or later.

**Comment by kefir500** [comment]
I made some changes to the build target, it should work now on macOS ≥ 10.13.
Could you please check if the [latest CI/CD build](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_macos_1.7.1.app.zip) works now on macOS 11.3.1?
