### ISSUE TITLE
ERROR unpacking APK

### ISSUE THREAD

**Issue by GuiRibi** [kefir500/apk-editor-studio#116]
tried different versions, different apks, downloaded countless times, navigated through the settings, nothing...

log:
java: Process failed to start: The system cannot find the file specified.

**Comment by kefir500** [comment]
You should install [Java](https://java.com/en/download/) on your machine.
If Java is already installed, you can specify the path to its directory in Settings → Options → Java → Java Path.

**Comment by GuiRibi** [comment]
> You should install [Java](https://java.com/en/download/) on your machine. If Java is already installed, you can specify the path to its directory in Settings → Options → Java → Java Path.

Oh my bad, thank you very much!
