### ISSUE TITLE
apktool --keep-broken-res support

### ISSUE THREAD

**Issue by g4rb4g3** [kefir500/apk-editor-studio#12]
It would be nice if you could add support for the --skip-broken-res switch of apktool.
It would avoid the following error and would APK Editor Studio allow to open those apks too.
![grafik](https://user-images.githubusercontent.com/646435/66072080-a208a580-e554-11e9-9a02-3e3d9d1e4501.png)

**Comment by kefir500** [comment]
Thanks for your input.

However, I can't find any mentions of the `--skip-broken-res` switch either in [docs](https://ibotpeaches.github.io/Apktool/documentation) or [sources](https://github.com/iBotPeaches/Apktool/search?q=skip-broken-res&type=Code). Am I missing something?

**Comment by g4rb4g3** [comment]
Sorry for that, I just googled the error and found that switch. It seems like it changed to --keep-broken-res sometime ago.

**Comment by kefir500** [comment]
Could you please provide a link to an APK with the described error so I could run some on tests on the `--skip-broken-res` switch?

**Comment by g4rb4g3** [comment]
I'll send you and apk file with mail. I think I'm not allowed to post my cars apk files somewhere on the net... And I don't have any other files causing this problem.

**Comment by kefir500** [comment]
Commit 6630161 adds the ability to specify the `--keep-broken-res` flag via GUI (*Options --> Repacking --> Decompile broken resources*). This feature will be included in the upcoming 1.3.0 release.
