### ISSUE TITLE
how to show smail to java 

### ISSUE THREAD

**Issue by chongbo2013** [kefir500/apk-editor-studio#122]
how to show smail to java 
![image](https://github.com/kefir500/apk-editor-studio/assets/3191545/d6b0fa8f-059d-4583-8e1e-6f72622e3ea0)

**Comment by root-kernelhacker** [comment]
Do you mean converting smali code to java source code?  If that's correct, apktool only converts to smali code from some point on.  It's not perfect, but github jadx is a tool that shows the code as a level of java code that you can refer to.

**Comment by kefir500** [comment]
Closing as duplicate of #112.
