### ISSUE TITLE
AhnLab-V3 PUP/Android.Malct.1191374 detect

### ISSUE THREAD

**Issue by root-kernelhacker** [kefir500/apk-editor-studio#123]
If you scan the apk file that has been built in Virus-Total, "AhnLab-V3PUP/Android.Malct.1191374" is detected.  Of course, I know that PUP is not a malicious code, and it means that there is unnecessary code, but I think it is better not to diagnose it if possible.

**Comment by kefir500** [comment]
Most likely, the reason is the publicly available *demo* key which is used for signing APK by default.
Have you tried signing APK with your own key?

**Comment by root-kernelhacker** [comment]
> Most likely, the reason is the publicly available _demo_ key which is used for signing APK by default. Have you tried signing APK with your own key?

I thought the default signing key would be fine on my own.  I did not create a personal signature key, but repackaged with default settings.  (In Virus Total Site, it is detected only in the Korean antivirus engine called ahnlab's v3) As you said, I will create a personal signature key and check it after applying it.  thank you !.

**Comment by kefir500** [comment]
Having the default key is handy. However, the main downside is its public availability. This means that any (potentially malicious) APK can be signed with it.

However, this is my first guess without detailed investigation, so I could be wrong. Let me know if the custom key works.

Regards,
Alexander

**Comment by root-kernelhacker** [comment]
> Having the default key is handy. However, the main downside is its public availability. This means that any (potentially malicious) APK can be signed with it.
> 
> However, this is my first guess without detailed investigation, so I could be wrong. Let me know if the custom key works.
> 
> Regards, Alexander

One guessed scenario is that Virus-Total only detects Ahnlab-v3, so I think it may be a false positive!.

**Comment by liushengqi000** [comment]
> Having the default key is handy. However, the main downside is its public availability. This means that any (potentially malicious) APK can be signed with it.
> 
> However, this is my first guess without detailed investigation, so I could be wrong. Let me know if the custom key works.
> 
> Regards, Alexander

custom key works. you are right :P

**Comment by kefir500** [comment]
Thank you for your feedback!
Closing the issue.
