### ISSUE TITLE
Error unpacking apk

### ISSUE THREAD

**Issue by markuptitan** [kefir500/apk-editor-studio#131]
![image](https://github.com/kefir500/apk-editor-studio/assets/110550090/1e479578-a769-40ea-9493-ea8ee1733e02)

I am new to this, matter of fact I discovered this app today and I am running Pop_OS!(Think of it as Ubuntu 22.04) and I am getting java:execvp: No such file or directory.

How can I deal with this?

**Comment by ahmedok2022** [comment]
Install java 8
