### ISSUE TITLE
Can't Run on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by iisbetoq** [kefir500/apk-editor-studio#132]
On website for macOS can run from 10.13 - 13 but on 10.15.7 can't run

> You have macOS 10.15.7. The application requires macOS 12.6 or later.

**Comment by restcure** [comment]
Please update the download page to reflect the required OS version.

**Comment by kefir500** [comment]
I made some changes to the build target.
Could you please check if the [latest CI/CD build](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_macos_1.7.1.app.zip) works on macOS 10.15.7?

**Comment by kefir500** [comment]
I made some changes to the build target.
Could you please check if the [latest CI/CD build](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_macos_1.7.1.app.zip) works now on macOS 10.15.7?

**Comment by iisbetoq** [comment]
> I made some changes to the build target, it should work now on macOS ≥ 10.13. Could you please check if the [latest CI/CD build](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_macos_1.7.1.app.zip) runs fine on macOS 10.15.7?

Hi, i have download and run smooth on macOS 10.15.7
<img width="1279" alt="Screen Shot 2024-08-11 at 14 10 10" src="https://github.com/user-attachments/assets/436617ac-8b32-4d4f-bd07-410432bbdea4">
Solved on macOS 10.15.7
Thanks
