### ISSUE TITLE
User Data not saving

### ISSUE THREAD

**Issue by Touchcreator** [kefir500/apk-editor-studio#133]
I modified an APK, however, all of my data is wiped when I close the app, and my progress is gone

**Comment by kefir500** [comment]
Do you mean something like saving your project in order to reopen it later without saving the APK first?
If yes, then check out [this](76) feature request.

**Comment by Touchcreator** [comment]
Turned out I had to change the hex code of a file in the apk lol

**Comment by kefir500** [comment]
Closing as duplicate.
