### ISSUE TITLE
Cloning and saving new apk FLAGS Trojan

### ISSUE THREAD

**Issue by VJVideophile** [kefir500/apk-editor-studio#134]
APK does not contain a virus when checked with VirusTotal.

When opened in Studio, cloned, renamed and saved, the APK now flags as containing "Trojan-Spy.AndroidOS.Banker"

Is there something malicious that has somehow sneaked in with the new Clone tool?

**Comment by kefir500** [comment]
Probably, the reason is the demo key.
Check out [this](123) issue for more info.

**Comment by VJVideophile** [comment]
Thanks, I'll check that out. Hopefully that'll fix it.

**Comment by kefir500** [comment]
Please, let me know if replacing the key with your own works fine.
