### ISSUE TITLE
PNG signature.

### ISSUE THREAD

**Issue by Eth030** [kefir500/apk-editor-studio#136]
I: Using Apktool 2.9.1
I: Copying C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b} classes.dex file...
I: Building resources...
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-mdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-mdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-xhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-xhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-xxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-de-xxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xxxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es-xxxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-es\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-fr-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res\drawable-fr-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\username\AppData\Local\Temp\brut_util_Jar_68032322710083037446390072275162551647.tmp, compile, --dir, C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\res, --legacy, -o, C:\Users\username\AppData\Local\Temp\apk-editor-studio\apk\{1a753b46-8700-4c78-a8bf-80e62f43bc9b}\build\resources.zip]

how can i ignore this

**Comment by Eth030** [comment]
I: Using Apktool 2.9.1
I: Copying C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08} classes.dex file...
I: Building resources...
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-mdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-mdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-xhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-xhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-xxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-de-xxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xxxhdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es-xxxhdpi\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-es\img_landing_carousel_chat.png: error: file failed to compile.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-fr-hdpi\img_landing_carousel_chat.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res\drawable-fr-hdpi\img_landing_carousel_chat.png: error: file failed to compile.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\eisah\AppData\Local\Temp\brut_util_Jar_90743007277958854752713089490404210222.tmp, compile, --dir, C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\res, --legacy, -o, C:\Users\eisah\AppData\Local\Temp\apk-editor-studio\apk\{0f6f497e-0af7-4b29-93aa-127efa3acd08}\build\resources.zip]

**Comment by kefir500** [comment]
Seems like a faulty PNG.
Check out [this issue](https://github.com/iBotPeaches/Apktool/issues/2202) from the Apktool repo.
