### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by julian20yt** [kefir500/apk-editor-studio#137]
can you fix this?
it says "java: Process failed to start: The system cannot find the file specified." #135

**Comment by Ibuprophen** [comment]
Have you checked to see if you have the most recent Java installed? 

https://www.java.com/en/download/manual.jsp

You may also want to check if your Java path is pointing to the Java Installation directory (others have mistakenly pointed to the Java Installer file). 

~Ibuprophen
