### ISSUE TITLE
Shazam not open

### ISSUE THREAD

**Issue by paulaner5** [kefir500/apk-editor-studio#14]
Hi, I can't open the Shazam APK.
It gives me an error: "Error unpacking APK."
Is there any way to solve it?
Thank you for your cooperation and good work

Paolo from Italy

**Comment by kefir500** [comment]
Hi,

- What detailed error text does it show when you click the "Error unpacking APK" line?
- Does this happen only to Shazam or to other apps, too?
- Please, provide a link to the APK so I could test it.

**Comment by kefir500** [comment]
Closing due to no reply. Reopen if needed.
