### ISSUE TITLE
Something Went Wrong: App Not Installed

### ISSUE THREAD

**Issue by TriTechX** [kefir500/apk-editor-studio#142]
I have had this issue too many times to count lately, and I'm simply trying to change a few assets in an existing APK. I signed and saved the APK perfectly fine using APK Editor Studio, and yet my phone (Pixel 7a) says that the "App was not installed." because "Something went wrong.". Am I doing something wrong in the program? All I did was modify the app title, icon, and a few assets of identical aspect ratio and resolution. The architecture of the app is arm 64 v8a and that matches my phone. Are there any additional steps I must take to make it compatible?

**Comment by kefir500** [comment]
Does this happen to all repacked APKs?
Have you tried removing the original APK from your phone before installing the new one?
Anyway, it's pretty hard to analyze the issue by the "Something went wrong" message.

**Comment by Katzover** [comment]
i have a galaxy a05 and i have the same issue that everything goes fine until i try to install it says app not installed with no more context
