### ISSUE TITLE
Error unpacking APK

### ISSUE THREAD

**Issue by S4r4h-O** [kefir500/apk-editor-studio#144]
Since I did not find any related issue, I met the following error:

![image](https://github.com/kefir500/apk-editor-studio/assets/128503216/716f39bb-844f-4ea4-a7fa-eb45f0cd3405)

I'm trying to edit this apk generated from ReVanced Manager, and have tried to change the path of file on my PC. Portable version, by the way.

**Comment by S4r4h-O** [comment]
I figured it out, installed Java Environment and restarted my PC. Now I'm facing the following issue:

I: Using Apktool 2.7.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Building resources...
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:12: error: resource android:color/bright_foreground_dark_disabled is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:162: error: resource android:color/btn_default_material_dark is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:163: error: resource android:color/btn_leanback_color is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:13: error: resource android:color/accent_device_default_700 is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:14: error: resource android:color/accent_device_default_50 is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:15: error: resource android:color/bright_foreground_dark_inverse is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:164: error: resource android:color/btn_default_material_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:165: error: resource android:color/btn_leanback_focused is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:16: error: resource android:color/background_floating_device_default_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:17: error: resource android:color/background_device_default_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:18: error: resource android:color/background_holo_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:19: error: resource android:color/background_floating_material_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:20: error: resource android:color/bright_foreground_disabled_holo_light is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:21: error: resource android:color/btn_colored_borderless_text_material is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:22: error: resource android:color/bright_foreground_dark is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:23: error: resource android:color/background_material_dark is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:24: error: resource android:color/btn_colored_text_material is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:25: error: resource android:color/car_blue_700 is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:26: error: resource android:color/background_floating_device_default_dark is private.
W: C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\res\values-v34\colors.xml:27: error: resource android:color/background_device_default_dark is private.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SAHOLI~1\AppData\Local\Temp\brut_util_Jar_63677444695385653504209887368766263762.tmp, link, -o, C:\Users\SAHOLI~1\AppData\Local\Temp\APKTOOL3950610587201214004.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544809920, --version-name, 19.09.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\SAHOLI~1\AppData\Local\Temp\APKTOOL3215159266293338318.tmp, -0, arsc, -I, C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\frameworks\1.apk, --manifest, C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\AndroidManifest.xml, C:\Users\Sah Oli\Downloads\APK Editor Studio v1.7.1\data\temp\apk\{ab442df7-c204-44a7-8fdb-051b7a436836}\build\resources.zip]

**Comment by kefir500** [comment]
Please, try updating to the latest Apktool (2.9.3):

`APK Editor Studio` → `Help` → `Check for Updates`
