### ISSUE TITLE
Not Displaying all Manifest information

### ISSUE THREAD

**Issue by MrSpoonie** [kefir500/apk-editor-studio#146]
Windows 11
Not Displaying Version Code, Minimum SDK or Maximum SDK when unpacking APK
Tested with multiple APKs
![Screenshot 2024-04-22 202025](https://github.com/kefir500/apk-editor-studio/assets/100389091/47468aa2-4c56-40c0-9090-4189b3f4b06e)

**Comment by kefir500** [comment]
Seems that the underlying third-party Apktool changed the YAML writer code which now doesn't cast numbers to strings. This breaks the regular expressions used to parse metadata in APK Editor Studio. I'll fix this in the next release.
