### ISSUE TITLE
saving apk

### ISSUE THREAD

**Issue by PolcioHubi** [kefir500/apk-editor-studio#148]
hey, I have a little problem or I'm stupid with saving the apk because when I try to save the apk, it saves but the size of the apk gets smaller, there is no change in the apk BUT other apps like subway surfers works
![Zrzut ekranu 2024-05-09 003434](https://github.com/kefir500/apk-editor-studio/assets/71091892/813f62c5-c69e-4437-938a-a3b31e07c388)
![Zrzut ekranu 2024-05-09 003253](https://github.com/kefir500/apk-editor-studio/assets/71091892/2e60a2b2-cc87-4ffa-b17f-6a63c51737d2)
![Zrzut ekranu 2024-05-09 003144](https://github.com/kefir500/apk-editor-studio/assets/71091892/9b4e6f04-fda2-4fb2-ad07-7da8c837e5db)

**Comment by kefir500** [comment]
Size difference between the original and the repacked APK is an expected behavior. Even without any changes, the repacking process can use different compression, different asset packing tool revisions, etc.
