### ISSUE TITLE
would not pack my apk

### ISSUE THREAD

**Issue by drherobrine9798** [kefir500/apk-editor-studio#15]
it keeps giving my errors sense i've installed this software and this is the error here is what it saying I: Using Apktool 2.4.0
I: Copying C:\Users\Keith\AppData\Local\Temp\apk-editor-studio\apk\{b1efa490-ec91-461d-a1a8-21717dd0b5e9} classes.dex file...
I: Building resources...brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\Keith\AppData\Local\Temp\brut_util_Jar_4684150323672512547.tmp, p, --forced-package-id, 127, --min-sdk-version, 3, --target-sdk-version, 28, --version-code, 871110004, --version-name, 1.11.0.4, --no-version-vectors, -F, C:\Users\Keith\AppData\Local\Temp\APKTOOL1333876901961663252.tmp, -0, png, -0, lang, -0, json, -0, fsb, -0, ogg, -0, jpg, -0, h, -0, txt, -0, nbt, -0, res/drawable-hdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-hdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, res/drawable-mdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-mdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, res/drawable-xhdpi-v4/com_facebook_tooltip_black_background.9.png, -0, res/drawable-xhdpi-v4/com_facebook_tooltip_blue_background.9.png, -0, mp3, -0, arsc, -I, C:\Users\Keith\AppData\Local\apk-editor-studio\frameworks\1.apk, -S, C:\Users\Keith\AppData\Local\Temp\apk-editor-studio\apk\{b1efa490-ec91-461d-a1a8-21717dd0b5e9}\res, -M, **C:\Users\Keith\AppData\Local\Temp\apk-editor-studio\apk\{b1efa490-ec91-461d-a1a8-21717dd0b5e9}\AndroidManifest.xml]**
![Capture](https://user-images.githubusercontent.com/59119229/71379513-951ab180-2599-11ea-8805-059ece52c5ea.PNG)

**Comment by kefir500** [comment]
Duplicate of #7. You should use 64-bit Java.
