### ISSUE TITLE
Regex is searching by groups instead of whole match

### ISSUE THREAD

**Issue by eried** [kefir500/apk-editor-studio#154]
Hi, awesome editor! I wonder why regex needs groups? even if I only search? (not replace)
Something like `const` that has thousand matches in the project, gives 0 matches with regex but `(const)` works ok

**Comment by kefir500** [comment]
Hi, thanks for your feedback!
Fair point :) Fixed the issue, you can check the latest automatic CI/CD build [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development).
