### ISSUE TITLE
Save the apk after opening the apk file

### ISSUE THREAD

**Issue by I-BlueDragon** [kefir500/apk-editor-studio#158]
I: Using Apktool 2.9.3
I: Copying C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835} classes.dex file...
I: Copying C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835} classes2.dex file...
I: Copying C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835} classes3.dex file...
I: Building resources...
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\head_default1.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\head_default1.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\image_qnet.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\image_qnet.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\qq_login.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\drawable\qq_login.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-hdpi\ic_launcher.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-hdpi\ic_launcher.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-hdpi\ic_launcher_round.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-hdpi\ic_launcher_round.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-mdpi\ic_launcher.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-mdpi\ic_launcher.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-mdpi\ic_launcher_round.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-mdpi\ic_launcher_round.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xhdpi\ic_launcher.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xhdpi\ic_launcher.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xhdpi\ic_launcher_round.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xhdpi\ic_launcher_round.png: error: file failed to compile.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xxhdpi\ic_launcher.png: error: failed to read PNG signature: file does not start with PNG signature.
W: C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res\mipmap-xxhdpi\ic_launcher.png: error: file failed to compile.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mr.ye\AppData\Local\Temp\brut_util_Jar_8312516888628175852949238098188677149.tmp, compile, --dir, C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\res, --legacy, -o, C:\Users\Mr.ye\AppData\Local\Temp\apk-editor-studio\apk\{9ea7fb6e-d62b-4ab3-8906-dc75c653a835}\build\resources.zip]

**Comment by kefir500** [comment]
Closing as [duplicate](136).
