### ISSUE TITLE
Configurable memory for external jar based tools

### ISSUE THREAD

**Issue by dubeyanurag** [kefir500/apk-editor-studio#16]
Application should allow changing available memory for jar execution, apktool can run much faster with more available memory.

**Comment by kefir500** [comment]
Do you mean the Java `-Xmx` switch?

**Comment by dubeyanurag** [comment]
> Do you mean the Java `-Xmx` switch?

Yes

**Comment by kefir500** [comment]
Added in 4442042.
This option will be included in the upcoming 1.4.0 release.
