### ISSUE TITLE
Cannot find Java in Windows

### ISSUE THREAD

**Issue by nthoait** [kefir500/apk-editor-studio#2]
My PC installed java and setup java path also, but when I open apk file it showed errors 

> Process failed to start: The system cannot find the file specified. ("java")
![Screenshot_8](https://user-images.githubusercontent.com/49742862/56338678-3795c000-61d5-11e9-854e-e147304c72d8.jpg)

Thanks!

**Comment by kefir500** [comment]
Is Java path present in your `PATH` \environment variable?

**Comment by nthoait** [comment]
> Is Java `bin` path present in your `PATH` environment variable?

Thanks, I declared it. and now it worked

**Comment by alex-ui** [comment]
It still doesn't work for me
