### ISSUE TITLE
Android explorer is not working in my PC !!

### ISSUE THREAD

**Issue by rayhansec** [kefir500/apk-editor-studio#20]
Hi there!
I happen to be a user of this software & really do admire for amazing works;. But sorry to say that android explorer is not being activated in my windows 10 PC.It would be great if u give some reply.
Best Regards.

**Comment by rayhansec** [comment]
!

**Comment by kefir500** [comment]
Hi,
Sorry for the delay.
Thank you for your feedback, I really appreciate it!

Could you please elaborate what exactly isn't working?
Are you experiencing problems while using the Android Explorer or maybe your device is not shown in the list?

**Comment by rayhansec** [comment]
Yes, android explorer is not working!!  i have my java installed in my
windows 10 pc. But even then, its not working..Do something.!!

**Comment by kefir500** [comment]
Please elaborate on how exactly Android Explorer isn't working.
Screenshots would also be helpful.

**Comment by rayhansec** [comment]
All I see is a blank android explorer that doesnt work..
![Capture](https://user-images.githubusercontent.com/64687384/83599072-1afd4880-a58d-11ea-9ffe-5486773ded57.PNG)

**Comment by kefir500** [comment]
Actually, this is not the Android Explorer. You are seeing the device list which is empty. In order to use ADB, you should enable USB debugging on your device. You can find the step-by-step instruction [here](https://developer.android.com/studio/debug/dev-options).

**Comment by rayhansec** [comment]
have u fixed ?

**Comment by rayhansec** [comment]
and how to do it ??

**Comment by kefir500** [comment]
I linked the official instructions in one of my previous messages: https://developer.android.com/studio/debug/dev-options#enable
