### ISSUE TITLE
An error when saving the APK

### ISSUE THREAD

**Issue by muslimomar** [kefir500/apk-editor-studio#21]
I'm trying to edit [alarmy ](https://play.google.com/store/apps/details?id=droom.sleepIfUCan&hl=en_US)app, but I get this error when I try to save the apk

Error Parsing APK.

`W: invalid resource directory name: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{b395a8bf-e0a8-4071-99a7-9a54484b1459}\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\muslim\AppData\Local\Temp\brut_util_Jar_3807460567675597666.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 29, --version-code, 42308, --version-name, 4.23.8, --no-version-vectors, -F, C:\Users\muslim\AppData\Local\Temp\APKTOOL1635734550941627566.tmp, -e, C:\Users\muslim\AppData\Local\Temp\APKTOOL8287019898804827416.tmp, -0, arsc, -I, C:\Users\muslim\AppData\Local\apk-editor-studio\frameworks\1.apk, -S, C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{b395a8bf-e0a8-4071-99a7-9a54484b1459}\res, -M, C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{b395a8bf-e0a8-4071-99a7-9a54484b1459}\AndroidManifest.xml]
`

**Comment by kefir500** [comment]
Try turning on AAPT2 in Settings -> Options -> Repacking.

**Comment by muslimomar** [comment]
Thanks for replying!
AAPT2 solved that issue, but now got a new bigger one : 

`I: Using Apktool 2.4.1
I: Copying C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c} classes.dex file...
I: Copying C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c} classes2.dex file...
I: Copying C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c} classes3.dex file...
I: Copying C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c} classes4.dex file...
I: Building resources...
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:540: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:541: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:542: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:543: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:544: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:545: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:546: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml:547: error: invalid value for type 'array'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\arrays.xml: error: file failed to compile.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml:15: error: invalid value for type 'plurals'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml:16: error: invalid value for type 'plurals'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml:17: error: invalid value for type 'plurals'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml:18: error: invalid value for type 'plurals'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml:19: error: invalid value for type 'plurals'. Expected a reference.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\plurals.xml: error: file failed to compile.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\public.xml:2418: error: resource 'drawable/$ic_backupsound_gradient_24_24__0' has invalid entry name '$ic_backupsound_gradient_24_24__0'. Invalid character '$ic_backupsound_gradient_24_24__0'.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\public.xml:2419: error: resource 'drawable/$ic_ico_purchase_newfeatures_gradient_24_24__0' has invalid entry name '$ic_ico_purchase_newfeatures_gradient_24_24__0'. Invalid character '$ic_ico_purchase_newfeatures_gradient_24_24__0'.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\public.xml:2420: error: resource 'drawable/$ic_ico_purchase_turnoffads_gradient_24_24__0' has invalid entry name '$ic_ico_purchase_turnoffads_gradient_24_24__0'. Invalid character '$ic_ico_purchase_turnoffads_gradient_24_24__0'.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\public.xml:2421: error: resource 'drawable/$ic_mission_typing_gradient_24_24__0' has invalid entry name '$ic_mission_typing_gradient_24_24__0'. Invalid character '$ic_mission_typing_gradient_24_24__0'.
W: C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res\values\public.xml:2422: error: resource 'drawable/$ic_mission_walking_gradient_24_24__0' has invalid entry name '$ic_mission_walking_gradient_24_24__0'. Invalid character '$ic_mission_walking_gradient_24_24__0'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\muslim\AppData\Local\Temp\brut_util_Jar_8728328140509795327.tmp, compile, --dir, C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\res, --legacy, -o, C:\Users\muslim\AppData\Local\Temp\apk-editor-studio\apk\{c806ce54-f7b4-4ffb-bf36-8da97da1447c}\build\resources.zip]`

**Comment by kefir500** [comment]
Seems that this error message is related directly to Apktool.
Check out this [issue](https://github.com/iBotPeaches/Apktool/issues/2271) for more information.

**Comment by muslimomar** [comment]
Yes. I actually tried with apktool and this issue happened. this is why I moved to Apk Editor Studio (didn't know it uses apktool).

**Comment by kefir500** [comment]
Sorry to hear that.
Closing this issue and waiting for the Apktool update.
Feel free to reopen if needed.
