### ISSUE TITLE
Add search (CTRL + F) support for xml and other text files in apk

### ISSUE THREAD

**Issue by muznyo** [kefir500/apk-editor-studio#22]

**Comment by kefir500** [comment]
Implemented in 3cc7ad8:

- **Find** functionality.
- **Replace** functionality.
- <kbd>Ctrl + F</kbd>, <kbd>Ctrl + H</kbd>, <kbd>F3</kbd>, and <kbd>Shift + F3</kbd> keyboard shortcuts.
- Real-time highlighting for all results (this might affect performance in large documents, so more tests should be done).

These features will be present in the upcoming 1.6.0 release.
Also, I'm planning to add more options (such as regular expressions, case sensitivity, etc.) in future versions.

You can check out the latest developer build [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development).
