### ISSUE TITLE
Support for relative tool paths

### ISSUE THREAD

**Issue by Cutetlaem** [kefir500/apk-editor-studio#25]
Currently, the software still does not support opening files with file names containing UTF-8 characters (when opening these files, you will receive an unpacking error). I hope the next update will support opening these files.
Also, the current version of ADB has the issue (although I don't know exactly what the problem is), please replace it with the latest version here: https://developer.android.com/studio/releases/platform-tools
When signing the APK I use a custom key, which is stored at `D:/APK Editor Studio/tools/mykey.jsk`. I want to use it in another computer, and for others (I'm using the portable version). But not everyone decompresses the software with the above path, so I hope the next version will have a path variable instead of just being able to use the absolute path as now.
> For example:
> Current: `D:/APK Editor Studio/tools/mykey.jsk`
> Next version: `%variable_path%/tools/mykey.jsk` (`%variable_path%` = `"Drive letter":/APK Editor Studio`)
> Or just: `tools/mykey.jsk` or `./tools/mykey.jsk` at "Keystore path".

In addition, please improve APK compression (can add the APK compression level menu in the settings so users can choose the APK compression level they want), by default raising it to 9 (highest). The current APK compression ability is much less than the APK Editor Pro software on Android.
Thanks very much.

**Comment by kefir500** [comment]
Thank you for your suggestions.

### UTF-8 filenames

Please, provide the following information:

1. An example filename
2. Your operating system

### ADB update

Since the SDK platform tools are downloaded on the pre-build phase using the [download script](https://github.com/kefir500/apk-editor-studio/blob/master/scripts/download.py#L66), the APK Editor Studio builds should contain the latest ADB version available at the time of the release.

### Relative paths

The `./` notation *does* work, however it refers to the current working directory which can be different from the application executable directory. The feature you mentioned could be really helpful with portable builds. I'll see what I can do, thanks for the idea.

### File compression

APK Editor Studio delegates the build process to the [Apktool](https://github.com/iBotPeaches/Apktool), so all (un)packing options are inherited from this third-party tool. I'm not familiar with APK Editor Pro, however my first guess is that it is using the ZIP compression which makes it possible to select different compression ratios.

**Comment by Cutetlaem** [comment]
> Thank you for your suggestions.
> 
> ### UTF-8 filenames
> Please, provide the following information:
> 
> 1. An example filename
> 2. Your operating system
> 
> ### ADB update
> Since the SDK platform tools are downloaded on the pre-build phase using the [download script](https://github.com/kefir500/apk-editor-studio/blob/master/scripts/download.py#L66), the APK Editor Studio builds should contain the latest ADB version available at the time of the release.
> 
> ### Relative paths
> The `./` notation _does_ work, however it refers to the current working directory which can be different from the application executable directory. The feature you mentioned could be really helpful with portable builds. I'll see what I can do, thanks for the idea.
> 
> ### File compression
> APK Editor Studio delegates the build process to the [Apktool](https://github.com/iBotPeaches/Apktool), so all (un)packing options are inherited from this third-party tool. I'm not familiar with APK Editor Pro, however my first guess is that it is using the ZIP compression which makes it possible to select different compression ratios.

### UTF-8 filenames:

1. Example: **Trình duyệt Via.apk** opening that file on the app will get an error because the file cannot be found, the file name displayed on the app is **Tr?nh duy?t Via.apk**
2. Operating system: Windows.

### ADB update:

I'm not sure, but I use the ADB download here: https://dl.google.com/android/repository/platform-tools-latest-windows.zip
Everything is working properly.

### Relative paths:

I am very grateful to you for that.

### File compression:

APK Editor Pro tool on Android can choose the compression level from 0 (uncompressed) - 9 (super-compressed). Whereas WinRAR has only 5 compression levels. I don't know exactly how the APK Editor Pro tool uses to compress but its compression is very good (but also uses a lot of the phone's CPU and Battery when using compression level 9). If you improve the compression capabilities of the software, fine. If not, then no problem!

**Comment by Cutetlaem** [comment]
Alternatively, if you can edit the `Decompile source code (smali)` function into a menu bar option after opening the APK file, one-click to instantly decompile the source code of the open APK file, instead of having to go to `Settings`, activate `Decompile source code (smali)` and reopen the APK file, at this point decompile source code (which is quite inconvenient).
That would be great!

**Comment by kefir500** [comment]
### UTF-8 filenames

Seems that the Java CLI doesn't properly support non-ASCII arguments on Windows, and APK Editor Studio relies heavily on Java (due to the Apktool dependency).

### ADB update

Yes, the same URL is used in the script referenced in my previous message :)

### File compression

As I mentioned before, APK Editor Studio is using Apktool under the hood. That means that the major repacking options are controlled by this third-party tool. Apktool, in its turn, is using Android AAPT for building which does not support different compression levels as far as I know.

### Source decompilation

Again, since APK Editor Studio delegates the unpacking functions to the Apktool, the source decompilation should be enabled on the initial unpacking step, therefore the repeated repacking is required anyway.

### Separate issues

Also, please create separate issues in future since it's much easier to track, tag and triage them in this way.

**Comment by Cutetlaem** [comment]
It seems the biggest hurdle here is Java because this software depends a lot on it. It beat most of my requests.
I'm just looking forward to `relative paths for the portable version` on the next version.
Set the label for this issue to `Feature`.
Thanks.

**Comment by kefir500** [comment]
Test support added in 770636e.
I will run more checks to make sure this feature works fine.
You can download the latest development build [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development).
Let me know if it works.

**Comment by Cutetlaem** [comment]
> Test support added in [770636e](https://github.com/kefir500/apk-editor-studio/commit/770636e612903c53c3b574fe28cabbd5693a11f7).
> I will run more checks to make sure this feature works fine.
> You can download the latest development build [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development).
> Let me know if it works.

I downloaded it and tried the `relative path` feature test. The file I use: `apk-editor-studio_win32_dev.zip`
When I use the drive `D:` the path is: `D:/APK Editor Studio/tools/mykey.jks`
I tried moving the folder `APK Editor Studio` to drive `C:` and check, the path I got was: `C:/APK Editor Studio/tools/mykey.jks`
However, the `Keystore` path located in the `config.ini` file at `Drive letter:\APK Editor Studio\data\config` is still saved as `Drive letter:/APK Editor Studio/tools/mykey.jks` instead of `./tools/mykey.jks` or `tools/mykey.jks`.
Everything is quite perfect, hope when officially released, the above problem has been fixed: On the tool can still display full `Drive letter:/APK Editor Studio/tools/mykey.jks` but in the file `config.ini` keep the path is `./tools/mykey.jks` or `tools/mykey.jks`.
Also, I hope the release will support storing `Keystore password` and `Key password` in `config.ini` files so that I don't have to rewrite them every time I use them (maybe as options, it's up to everyone's preference. want to save or not, encrypt them or not, does not matter).
P/s: I haven't tried signing the app yet because my app hasn't been updated to the new version yet. Hence, I still don't know if it really works or not. 😅

**Comment by kefir500** [comment]
- You should specify a *relative* path in the "Keystore path" field. Also, the b44ead3 commit contains a minor fix for this input field.
- Currently the ability to save passwords is powered by platform-specific managers, which is considered relatively safe and reliable way to store secret data. The ability to store passwords (encrypted or not) in a config file creates a serious security breach even as an optional feature.

**Comment by Cutetlaem** [comment]
> * You should specify a _relative_ path in the "Keystore path" field. Also, the [b44ead3](https://github.com/kefir500/apk-editor-studio/commit/b44ead35241174612b62c68903349a672d6df832) commit contains a minor fix for this input field.
> * Currently the ability to save passwords is powered by platform-specific managers, which is considered relatively safe and reliable way to store secret data. The ability to store passwords (encrypted or not) in a config file creates a serious security breach even as an optional feature.

I tried specifying a relative path to `./tools/demo.jks` and then hit "OK". But the tool automatically updates the path to `Drive letter:/APK Editor Studio/tools/demo.jks` in the "Keystore path" field. I think should use something like replace `./` to `Drive letter:/APK Editor Studio/` when displayed and when saving to the config file replace `Drive letter:/APK Editor Studio/` to `./`.

**Comment by kefir500** [comment]
Did you try the latest build?

> But the tool automatically updates the path "Keystore path" field

Actually, it should save the proper relative path. There was a minor bug: when you reopen the Key Manager dialog, the field value is reset to an absolute path. This issue was fixed in the [commit](b44ead3) mentioned in my previous message :)

**Comment by kefir500** [comment]
I mean, did you redownload it after [this message](https://github.com/kefir500/apk-editor-studio/issues/25#issuecomment-674454100)?

**Comment by Cutetlaem** [comment]
Okay, I tried reloading later, the relative path seems to work, when I tried typing "./tools/demo.jks" in the "Keystore path" field and then hit OK, the tool didn't update path to the absolute path, hope it works fine in the release.
I'm waiting for it to be released! 😄
