### ISSUE TITLE
APK is nowhere to be found when I click "save as"

### ISSUE THREAD

**Issue by Rex501st** [kefir500/apk-editor-studio#26]
I have no Idea what is causing this, but I am trying to edit Peacock TV to make the icon display properly.

**Comment by kefir500** [comment]
- Perhaps you mean `Save APK`? Because `Save As` is intended for saving a resource in the active editor.
- If yes, then are you getting any error messages?
- Where exactly are you saving your APK? Have you tried saving to other locations?

**Comment by ArestouMars** [comment]
> 
> 
>     * Perhaps you mean `Save APK`? Because `Save As` is intended for saving a resource in the active editor.
> 
>     * If yes, then are you getting any error messages?
> 
>     * Where exactly are you saving your APK? Have you tried saving to other locations?

Yes, sorry, I mean **Save APK**. I am not getting any error messages. I have tried my desktop, documents and downloads folder.

**Comment by kefir500** [comment]
Sorry for the delay.

That's a very strange issue.
- Does this happen to other APKs, too?
- Have you tried rebuilding this APK manually using the [Apktool](https://github.com/iBotPeaches/Apktool)? This tool is used by APK Editor Studio under the hood, and the output file is generated by directly running it.

**Comment by AmyKona** [comment]
error unpacking apk
![Uploading Screenshot 2021-02-23 220952.png…]()

how to solve this issue?

**Comment by kefir500** [comment]
@AmyKona
Please, provide a full error message which can be revealed by clicking the red error line.
Also, create a separate issue since your question is not related to this discussion.

**Comment by kefir500** [comment]
Closing due to no reply.
Reopen the issue if needed.
