### ISSUE TITLE
Bundletool implementation

### ISSUE THREAD

**Issue by ibuprophen1** [kefir500/apk-editor-studio#3]
@kefir500, I was just wondering if you had any plans for implementing the following BundleTool (jar) within the Studio Software?

https://github.com/google/bundletool

A friend of mine had asked me about the BundleTool and, after looking into it, I thought that it would be interesting to see if you could do anything with it. 

Thanks a bunch! :-)

~Ibuprophen

**Comment by kefir500** [comment]
Building Android bundle with `bundletool` involves a separate compilation chain as described [here](https://developer.android.com/studio/build/building-cmdline#bundletool-build). E. g. this requires `AAPT2` (to compile resources, protocol buffer, etc.) which is already present in `Apktool`.

As APK Editor Studio delegates the APK build chain to `Apktool`, the `bundletool` support is not planned to be implemented.

**Comment by talk22** [comment]
Hello Everyone !
The problem we are currently facing is as follows:
How to compile APK file in AAB format, with the APK EDITOR STUDIO tool? Of course we are talking about a necessary new update
Is there any additional information?

**Comment by kefir500** [comment]
Hi @talk22,
The latest discussion is located [here](https://github.com/kefir500/apk-editor-studio/discussions/42).

**Comment by talk22** [comment]
And for reference!
Why don't you try to improve the interface of the tool, 
for example, APK Easy Tool is one of the best reverse engineering tools

**Comment by kefir500** [comment]
@talk22

APK Editor Studio and APK Easy Tool aim at completely different functions. While APK Easy Tool indeed has a simpler interface and some interesting solutions, APK Editor Studio is an IDE-like software with lots of built-in utilities, such as:

- Resource inspector
- Code editor
- Icon editor
- Title editor
- Manifest editor
- …

Personally, I don't see how you can bundle all this stuff in an intuitive minimalistic interface. Providing more functions leads to a more complex design. Of course, there are certain aspects to work on and improve, but it's definitely not about rewriting the core GUI concept. Probably, I will introduce an alternative simplified view for the main window in future releases, but it's not in my todo-list at the moment.

Coming back to the comparison, APK Easy Tool is a handy tool when the primary target is to *manually* perform the aforementioned operations. APK Editor Studio, on the other hand, contains all these tools out of the box as a part of its GUI. So the bottom line is that each of these apps has its own use cases.

Also, in the future, please create separate issues for comments not related to the topic.
