### ISSUE TITLE
Readme - Add info about Java JDK and JAVA_HOME variable

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#33]
@kefir500 

I propose you to add in README, for Windows user info about program requirement 

- Install Java JDK
- set JAVA_HOME variable that point to latest build of JDK folder.

Thanks.

**Comment by kefir500** [comment]
Usually the corresponding environment variables are automatically updated by the Java installer. Also, README in this repo mostly refers to the process of building from sources, and Java is not a requirement in this chain, so I think the **Requirements** section on the website download page should be enough.
