### ISSUE TITLE
C:/Java/jdk-12.0.2_windows-x64_bin.exe/bin/java: Process failed to start: System cannot find specified file

### ISSUE THREAD

**Issue by alex-ui** [kefir500/apk-editor-studio#34]
I installed the program and when I open an APK, it returns this error. I added all the java paths, including the bin folders, and it still doesn't work. I reinstalled Java multiple times but I am unable to fix this problem. Issue #2 is similar to this, but the solution that I saw there didn't work, and since it was closed I couldn't ask. Need help.

The original error is in spanish:

`C:/Java/jdk-12.0.2_windows-x64_bin.exe/bin/java: Process failed to start: El sistema no puede encontrar el archivo especificado.`

**Comment by kefir500** [comment]
According to the error message, it seems that you are providing the path to the Java installer, not the installation directory itself.
