### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by ReynaYValera** [kefir500/apk-editor-studio#36]
Cannot find a way to hide Navigation Bar before re-compiling.

**Comment by kefir500** [comment]
There is no dedicated function to remove navigation bars or similar elements in the APK Editor Studio user interface. However, you are free to explore and edit (if the application license allows) the unpacked resources and the disassembled source code (if the `Settings → Repacking → Decompile source code (smali)` option is enabled).

This issue tracker is primarily intended for questions, ideas, and bugs related directly to the APK Editor Studio. You might want to ask the APK-specific questions in the APK modding threads located on the thematic forums, such as XDA Developers.
