### ISSUE TITLE
GUI issues (strings not translated)

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#45]
@kefir500 

I found some issues in GUI as strings untranslated

![image](https://user-images.githubusercontent.com/1262554/132314835-c3307b4d-3440-4475-9a46-01a52696d9f6.png)

- Untranslated string

![image](https://user-images.githubusercontent.com/1262554/132315184-51b06a71-9186-4bf7-9109-572c5561a6ab.png)

- Link show as text instread as link

![image](https://user-images.githubusercontent.com/1262554/132314863-b3e3379b-15b1-40e5-b5a4-f430c183c3b7.png)

- Untranslated string.

Thanks.

**Comment by kefir500** [comment]
Hi @bovirus,
Thanks for the heads up!

- [x] **Screenshot 1** – Fixed in 8aeffbf. I'll upload the new strings to Transifex in the nearest future.
- [x] **Screenshot 2** – Fixed in 15ed829. For some weird reason, Qt wasn't detecting the rich text format in Italian.
- [ ] **Screenshot 3** – There is a bunch of new features to be translated. Again, I'll update the Transifex string in the nearest future.

**Comment by bovirus** [comment]
@kefir500 

Thanks.
Italian language updated (18 new strings translated).

**Comment by kefir500** [comment]
I've just added 2 more strings that were missing.
Thanks for keeping the Italian translation up-to-date!

**Comment by bovirus** [comment]
@kefir500 

Done also 2 new strings.
Thanks.

**Comment by kefir500** [comment]
@bovirus Yes, I have also faced the lack of notifications from Transifex. There are also some UI decisions I don't really like, to be fair. Though Transifex is a good service that helped us a lot, I'm thinking of migrating to Weblate in the future.

**Comment by bovirus** [comment]
@kefir500 

Also weblate is a good service.
But I'm not sure that it's free.

Note: i didn't have any problem with notification by Transiflex.
For me the Transiflex notification service works fine and of the better system for this.
Infact today I received the notification about your update about language files.
And after i received the notification I clcik on the notificatipona and I updated the new strings for Italian language.

**Comment by kefir500** [comment]
Weblate is available for free as a self-hosted service.
Well, at least if we don't count paying for the hosting itself :)
It also seems that Weblate is free for open-source projects, just as Transifex.

**Comment by bovirus** [comment]
@kefir500 

It's important of course that notiufication service A8about new content) works fine.
