### ISSUE TITLE
C++ alternatives to JAVA tools

### ISSUE THREAD

**Issue by Symbian9** [kefir500/apk-editor-studio#5]
Are there `C++` implementations of  `apktool.jar`, `apksigner.jar` and `demo.jks`?

For make *APK Editor Studio* fully free of JAVA/JRE dependencies?

**Comment by kefir500** [comment]
APK Editor Studio heavily depends on multiple third-party tools which are not available in C++.

- [`apktool.jar`](https://github.com/iBotPeaches/Apktool) is implemented only in Java .
- [`apksigner.jar`](https://developer.android.com/studio/command-line/apksigner) is a part of Android SDK Build Tools. AFAIK, there are no C++ implementations.
