### ISSUE TITLE
Error packing APK [java: execvp: No such file or directory]

### ISSUE THREAD

**Issue by ducpv-1644** [kefir500/apk-editor-studio#54]
I use `Ubuntu 20.04.3 LTS` and run version `apk-editor-studio_linux_1.6.0.AppImage`
But I can't open apk file while my file is in the Download folder

![Screenshot from 2021-12-03 15-32-13](https://user-images.githubusercontent.com/48663821/144570956-238b784a-8943-4449-b5af-de204702bdb2.png)

Some help? Thanks in advance

**Comment by kefir500** [comment]
You should install Java on your machine.
