### ISSUE TITLE
Problem with Italian text in 'Save as' dialog

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#55]
@kefir500 

Hi.

![image](https://user-images.githubusercontent.com/1262554/147405114-df34248e-4567-4c32-9791-fd409ffe3af0.png)

i found an error in "Save as" window.
But I didn't find this text in APKE ditor Studioop language file.

Is this text part of standard qt localization?

Thanks.

**Comment by kefir500** [comment]
Hi,

If I understand correctly, this string describes the replacement of the existing file.
If so, then yes, this string is a part of the standard Qt localization.
