### ISSUE TITLE
APK Editor Studio 1.6.0 - CR/LF not get in language file

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#56]
@kefir500 

In language theer some long strings that for me could be read better if you break any paragraph with nel line.

Ex.

**You are using the built-in keystore provided for demonstrational purposes. It can be practical for testing or personal usage. However, if you plan to distribute this APK, we recommend you to specify/create your own keystore via Key Manager.**

For me this strings is too long withoutr CR/LF and can be better readable like this

**You are using the built-in keystore provided for demonstrational purposes.** 

**It can be practical for testing or personal usage.**

**However, if you plan to distribute this APK, we recommend you to specify/create your own keystore via Key Manager.**

In Italian .ts file I used new line but it didn't show right (it seems that for this string new lien is not recognzied).

It works if instead new line I used **< br / >** (without space - just to show it).

Is it normal?
When I should use < br / > instead newline?

**Comment by kefir500** [comment]
For plain text, Qt expects `\n`.
For rich text (containing tags, such as `<a>`, `<b>`, etc.), Qt expects `<br>`.
This particular string (regarding the demo keystore) is used in the `RememberDialog` class which is forced to parse the rich text.
