### ISSUE TITLE
APK Editor Studio - didn't read "assset" folder

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#57]
@kefir500 

I have an app where the localization are in text files in "asset" subfolder.

But opening the apk file with APK Editor Studio it didn't show "asset" subfolder.

If I rename a.pk as apk.zip and open with decompressor I can see "asset" folder.

You can gete the apk file from here (my mega repository)

https://mega.nz/file/XcoACLbD#WPZGPNd9XcejQ54SHqmB_8ftme4n6YJYtfuscXkNfBI

What's the matter?

**Comment by kefir500** [comment]
Are you sure you are looking in the right panel?
The "Resources" panel is intended for the parsed `res` directory, that's why it doesn't display the `assets`.
However, if you open the "File System" panel, you'll see the `assets` directory and its contents.
