### ISSUE TITLE
Compare with APK Studio

### ISSUE THREAD

**Issue by Symbian9** [kefir500/apk-editor-studio#6]
How *APK Editor Studio* could be compared with *APK Studio*?

- https://github.com/vaibhavpandeyvpz/apkstudio

**Comment by kefir500** [comment]
Never used APK Studio, so I can't really compare these tools.
However, you can see the APK Editor Studio highlights [here](https://qwertycube.com/apk-editor-studio/blog/apk-editor-studio-v1.0.0-released/).

In short:
- Application icon editor
- Application title editor
- Application TV banner editor
- Code editor
- Image replacer
- Resource inspector
- Simple manifest editor
