### ISSUE TITLE
Possible Solution For Some... 

### ISSUE THREAD

**Issue by Ibuprophen** [kefir500/apk-editor-studio#65]
Hello Again My Friend @kefir500 ! 

I was just thinking that little/some/none of the issues may/might be resolved if the latest Apktool https://github.com/iBotPeaches/Apktool/releases/tag/v2.6.1 was being used. 

Though I do update it manually in the software, some may not be, and maybe if you release another version of your great work with the latest version included. 

Just a thought... 👍 

Thanks a Bunch! 

~Ibuprophen

**Comment by kefir500** [comment]
Hi @Ibuprophen,
Long time no see :)

I've been really busy at my full-time job.
Finally, I have some spare time to clean up the issues :)

You're absolutely right: an up-to-date Apktool is *the* solution for most issues.
Considering the lack of spare time to work on the APK Editor Studio, I decided to [implement](https://github.com/kefir500/apk-editor-studio/commit/64352bfee579deecd371230840a998e4dba481c8) an automatic Apktool updater for the upcoming APK Editor Studio release. It will keep the Apktool up to date without having to wait for the next APK Editor Studio version.
