### ISSUE TITLE
Missing .java view..?

### ISSUE THREAD

**Issue by eGit** [kefir500/apk-editor-studio#66]
I only see unreadable smali files. Maybe I am missing something, but a .java source view would be nice?

Or is this not within the scope of this software and you recommend additional tools to convert .smali into .java files?

**Comment by kefir500** [comment]
Hi @eGit,

APK Editor Studio uses [Apktool](https://github.com/iBotPeaches/Apktool) under the hood for (un)packing APK files, and it works only with `.smali` sources. Currently, there are no plans to implement the `.java` decompilation.

I've never used it myself, but you can check out [this project](https://github.com/skylot/jadx) and see if it fits your needs.
