### ISSUE TITLE
Editing smali files.

### ISSUE THREAD

**Issue by RoHBee** [kefir500/apk-editor-studio#68]
I am really newbie here and I didn't find proper place to ask this. 
How to edit .dex files using this tool. All I see is unzipped apk file. There's no option to decompile apk or choose a decompiled one.

TL;DR
How to edit dex/smali files?

**Comment by Ibuprophen** [comment]
@RoHBee, There's a couple of Editors I've used, but the following one is typically my go-to editor for certain files like those. 

https://notepad-plus-plus.org

It took a little time for me to get familiar with it (as well as plugins for it too). It's also free too. 

I can't endorse anything specific as everyone has they're own flavor based upon various files, needs, wants, etc..., but that would be a good start. 

Good Luck! :-)) 

~Ibuprophen

**Comment by RoHBee** [comment]
thanks :)

**Comment by kefir500** [comment]
Hi @RoHBee,
Sorry for the delay.

Actually, you can edit the `smali` files directly in the APK Editor Studio!

1. Enable the `Settings` → `Options` → `Apktool` → `Decompile source code (smali)` checkbox.
2. Open your APK.
3. Switch to the `File System` tab in the bottom left dock.
4. There you can find `.smali` files and edit them in the build-in code editor. Syntax highlighter included :)

Kindest regards,
Alexander
