### ISSUE TITLE
Error packing APK located under non-ASCII path

### ISSUE THREAD

**Issue by Libert-y** [kefir500/apk-editor-studio#71]
I: Using Apktool 2.6.0
I: Copying C:\Users\Liberty\Desktop\{910ceb81-f6e6-4ecb-b887-221faadbf9ca} classes.dex file...
I: Building resources...
W: C:\Users\Liberty\Desktop\{910ceb81-f6e6-4ecb-b887-221faadbf9ca}\res: error: failed to open directory: System cannot found the file. (2).
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Liberty\AppData\Local\Temp\brut_util_Jar_8751596977623440592188767050080764231.tmp, compile, --dir, C:\Users\Liberty\Desktop\{910ceb81-f6e6-4ecb-b887-221faadbf9ca}\res, --legacy, -o, C:\Users\Liberty\Desktop\{910ceb81-f6e6-4ecb-b887-221faadbf9ca}\build\resources.zip]

**Comment by magnus-ISU** [comment]
I'm trying to use this, getting the same last line too. I'm unsure whether that is a real error in running some java thing which isn't installed properly alongside the app, or whether the line above (`W: something something error`) is an actual error and not a warning as W implies.

```
I: Using Apktool 2.6.0
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes8.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes7.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes6.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes5.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes4.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes3.dex file...
I: Copying /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba} classes2.dex file...
I: Building resources...
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:628: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:629: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:630: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:631: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:632: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:633: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:634: error: unexpected element <uses-native-library> found in <manifest><application>.
W: /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml:635: error: unexpected element <uses-native-library> found in <manifest><application>.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_116959985949077475974213791539222566406.tmp, link, -o, /tmp/APKTOOL11926046179450493718.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 84635, --version-name, 11.92.0.33, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /tmp/APKTOOL9995174260898869041.tmp, -0, arsc, -I, /home/mag/.config/apk-editor-studio/frameworks/1.apk, --manifest, /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/AndroidManifest.xml, /tmp/apk-editor-studio/apk/{d36d7c45-4972-4177-b5a4-d81bd8dc62ba}/build/resources.zip]
```
^^^ me trying to simply repackage snapchat after opening the APK and not doing anything.

**Comment by freMea** [comment]
> I: Using Apktool 2.6.0 I: Copying C:\Users\Liberty\Desktop{910ceb81-f6e6-4ecb-b887-221faadbf9ca} classes.dex file... I: Building resources... W: C:\Users\Liberty\Desktop{910ceb81-f6e6-4ecb-b887-221faadbf9ca}\res: error: failed to open directory: System cannot found the file. (2).

I got the same error and I solved it locating the *[APK Editor Studio](https://qwertycube.com/apk-editor-studio/download/)* folder in a path with no accent and space. Safely, locate it in a root of a drive.

Maybe the app should have a check of is own path and warn user if it is pron to fail during building APK.

**Comment by kefir500** [comment]
Hi everyone,
Sorry for the delay.

@Libert-y, @Fred-Vatin,
That's a pretty weird issue.
Are you using an installable MSI or a portable ZIP build?

@magnus-ISU,
Your error is non related to this subject.
Please, try the latest APK Editor Studio 1.7.0 and create another issue if the error is still present.

**Comment by Fred-Vatin** [comment]
> @Libert-y, @Fred-Vatin, That's a pretty weird issue. Are you using an installable MSI or a portable ZIP build?

Portable zip

**Comment by kefir500** [comment]
@Fred-Vatin, could you please share the Apktool output path?
It can be found in Settings → Options → Apktool → Extraction Path (value or placeholder)

**Comment by Fred-Vatin** [comment]
The current one is OK. Still using 1.6.
![image](https://user-images.githubusercontent.com/22337329/209922651-f871ea48-58ed-4ba5-b052-79289396a35a.png)

The problematic path can be retrieved by replacing `D:` by `D:\Programmes\Téléphone` on the path above.

**Comment by kefir500** [comment]
Thanks for your feedback, I'll investigate the issue.

**Comment by kefir500** [comment]
Hi again,

@Fred-Vatin
I've just noticed the `é` character in your path.

Java is famous for its [poor support](https://bugs.openjdk.org/browse/JDK-4488646) for non-ASCII characters on Windows. The solution is to change the output path in `Settings → Options → Apktool → Extraction path` (or like you did).

So this issue is not related to APK Editor Studio. However, I agree with you about showing an explicit message to warn users of this Java problem. I've created [this issue](https://github.com/kefir500/apk-editor-studio/issues/103) for future APK Editor Studio releases.

Most likely, @Libert-y has the same issue.
Seems that the original error log was edited (according to the path and minor mismatches in the Apktool warning message).

**Comment by gncerkan** [comment]
**Error packing APK.**
Hello. I wanted to use the app to change name and icon but after clicking “save APK” i get error like this. 
My app version is 1.7.2 and Apktool version is 2.11.0. I also installed Java and Visual C+. 
I also changed the “extraction path” path but the problem is not solved.
Please help me. 
```
I: Using Apktool 2.11.0 on tvQuickActionsPro_v3.5.4.apk with 8 threads
I: Copying raw classes.dex file...
I: Building resources with aapt2...
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\raws.xml:3: error: invalid value for type 'raw'. Expected a reference.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\raws.xml: error: file failed to compile.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\xmls.xml:3: error: invalid value for type 'xml'. Expected a reference.
W: C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res\values\xmls.xml: error: file failed to compile.
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mustafa\AppData\Local\Temp\brut_util_Jar_13568560043197526301127540768758976464.tmp, compile, --dir, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res, --legacy, -o, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\build\resources.zip]
	at brut.androlib.AaptInvoker.invoke(SourceFile:0)
	at brut.androlib.ApkBuilder.buildResources(SourceFile:0)
	at brut.androlib.ApkBuilder.build(SourceFile:0)
	at brut.apktool.Main.main(SourceFile:0)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mustafa\AppData\Local\Temp\brut_util_Jar_13568560043197526301127540768758976464.tmp, compile, --dir, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\res, --legacy, -o, C:\APKEditorStudio\apk\{a0f77249-568d-4afd-9268-a3c92bf07555}\build\resources.zip]
	at brut.util.OS.exec(SourceFile)
	... 4 more
```
