### ISSUE TITLE
"error unpacking apk"

### ISSUE THREAD

**Issue by distributer-on-discord** [kefir500/apk-editor-studio#73]
every time I try to open any APK it gives an error saying it was unable to find the file specified and nothing works with it, I don't know why

**Comment by nad1ax** [comment]
Install [Java](https://www.java.com/en/download/)

**Comment by kefir500** [comment]
Hi @distributer-on-discord,
Sorry for the delay.

It is hard to guess from your message the exact file missing.
However, most likely @nad1ax is right: you should install Java.

If this doesn't help, feel free to reopen the issue and provide a more detailed error message.
