### ISSUE TITLE
Problem Error unpacking APK

### ISSUE THREAD

**Issue by SWxEng** [kefir500/apk-editor-studio#75]
Hi @kefir500 
.
Problem 
Error unpacking APK
java: Process failed to start: The system cannot find the file specified.
.
![image](https://user-images.githubusercontent.com/55116927/192901580-816cda39-89fa-4b04-ae0b-565430e06c38.png)

**Comment by kefir500** [comment]
Hi @SWxEng,
You should install [Java](https://www.java.com/en/download/) on your machine.

**Comment by SWxEng** [comment]
Yes, and the problem was solved
