### ISSUE TITLE
Decompiling process fails for some APKs

### ISSUE THREAD

**Issue by knowpwr** [kefir500/apk-editor-studio#77]
Hello. I have noticed that when some APKs contain .dex **assets** files, the smali decompilation fails. This is mentioned in here and there is a solution for it with the issue too:

https://github.com/iBotPeaches/Apktool/issues/2833

I suggest adding the option to smali main classes only as part of the interface.

Thanks for your time.

**Comment by kefir500** [comment]
Hi @knowpwr,
Thanks for the heads up!
Implemented in 071dbc1.
