### ISSUE TITLE
[request] Allow users to save projects

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [kefir500/apk-editor-studio#78]
It would be amazing if we could save projects, e.g. save the contents of the apk in the folder, and be able to come back to it, without saving the apk. I really hate how the program deletes the folder when you exit apk editor studio.

Please have it keep the extracted apk folder. Also, please allow users to open folders as extracted apks. That way the editing process will be much much better, as changes will stay saved, even if you don't pack the apk.

**Comment by kefir500** [comment]
I agree, this would be handy.
I'm closing this issue as duplicate since this feature was already requested [here](https://github.com/kefir500/apk-editor-studio/issues/76).
