### ISSUE TITLE
Ability to specify Java path

### ISSUE THREAD

**Issue by TiberiumFusion** [kefir500/apk-editor-studio#8]
This program appears to have an unreliable means of determining the correct version of Java to run. Here is the situation on my PC:
1. I launch APK Editor Studio
2. I click Open APK and pick one.
3. Log messages appear:
> Unpacking APK...
> Error unpacking APK.

3a. The details for "Error unpacking APK." are as follows:
> Error: Registry key `'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'`
has value '1.8', but '1.7' is required.
> Error: could not find java.dll
> Error: Could not find Java SE Runtime Environment.

How strange. I inspect the program events with Process Monitor. Here's what I've surmised.
1. After clicking Open APK, APK Editor Studio checks the registry path `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\java.exe`.
1a. Is it trying to locate the most current version of java.exe? This bizarre-looking key is very unusual and does not exist on any of my PCs. Why not use the Path and/or JAVA_HOME vars?
1b. Presumably, APK Editor Studio defaults to some fallback, since the registry key does not exist.
2. APK Editor Studio launches `%windir%\SysWOW64\java.exe`.
2a. Is this a hardcoded default path? No matter where this magic path comes from, it is not a good choice. That particular java.exe doesn't seem to be dependable. It is merely a copy from the actual Java install location and only exists on one of my PCs. Furthermore, the 1.8 JDK and JRE installers do not overwrite it with the latest java.exe, so it has remained at 1.7 for a long time (on my PC).
3. The launched java.exe (again, version 1.7) checks the registry key `HKLM\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\CurrentVersion`. It reads 1.8, determines it is outdated, and terminates.
4. This is likely the point where APK Editor Studio reports the errors.
4a. The registry path provided by the APK Editor Studio's error message (`'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'`) is highly questionable. There is no hive specified. On my PC, the closest match is `HKLM\Software\JavaSoft\Java Runtime Environment\CurrentVersion`, and that key was never even read, as detected by Process Monitor.

**Comment by Ibuprophen** [comment]
I had seen a similar issue on the Apktool issues and found that some individuals resolved their issue by removing/uninstalling the Java for 32-bit systems and then installing the Java for 64-bit systems. 

It just may, hopefully, work for you... 


~Ibuprophen

**Comment by TiberiumFusion** [comment]
@Ibuprophen I'm afraid that, in my situation, total loss of x86 Java is a pretty steep price to pay. That is, half of my tools which depend on the 32 bit JRE will be rendered useless.

If this is an Apktool tool issue, I hope the are able to correct their software soon.

**Comment by Ibuprophen** [comment]
I've actually got both the 32-bit and 64-bit java installed on my PC for quite some time now and I haven’t encountered any issues (so far). 

According to what iBotPeaches had stated on the https://github.com/iBotPeaches/Apktool/issues/2148#issuecomment-522226099, he plans to release Apktool v2.4.1 sometime soon. 

Let's keep our fingers crossed! :-) 


~Ibuprophen

**Comment by kefir500** [comment]
@TiberiumFusion APK Editor Studio doesn't use explicitly specified hard-coded binary/registry paths. It simply runs the Java picked from the `PATH` environment variable, which in general is identical to calling the `java` command from CLI.

The same method is used in many other applications: this allows users to define a system-wide Java. However, I think that ability to manually select a specific Java executable in APK Editor Studio settings would be helpful. If you don't mind, I'll rename this issue to "Ability to specify Java path" as there is nothing to do with the Java detection since APK Editor Studio relies on paths specified in the system.

**Comment by kefir500** [comment]
Ability to manually specify the Java location is introduced in 6861471. This feature will be present in the upcoming 1.3.0 release.
