### ISSUE TITLE
apksigner does not verify apks signed by apk editor

### ISSUE THREAD

**Issue by Nottt** [kefir500/apk-editor-studio#9]
I added my own keystore, and when I edit a file and save it, and transfer ir to my linux box, and verify it using apksigner 0.8 it says this:

```
apksigner verify --verbose --print-certs -Werr 3.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Number of signers: 1
Signer #1 certificate DN: CN=XXX, OU=XXX, O=XXX, L=XX, ST=XX, C=XX
Signer #1 certificate SHA-256 digest: 6d10f63293b22811e3594fda32046bebb2a14fd5f60e56179aa1d0ddeff20882
Signer #1 certificate SHA-1 digest: 44396f81ce9153e62cba10e427e556cb86fdbaae
Signer #1 certificate MD5 digest: b03255f394c102752dde18e2729717e5
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: 2356ebc8b84b8d4d0b7849052bc3e8b2a7ea67863f3ed720d5d9f125be340821
Signer #1 public key SHA-1 digest: befe52c988993ba380542727c2e90818fd0c09d4
Signer #1 public key MD5 digest: 684a1e6aac5d9c9be38b7713134b326c
WARNING: JAR signer UPLOAD.RSA: JAR signature META-INF/UPLOAD.SF references unknown APK signature scheme ID: 3
WARNING: APK Signature Scheme v2 signer #1: Unknown signature algorithm: 0x421
```

**Comment by kefir500** [comment]
APK Editor Studio runs the following command to sign APK:
````
java -jar apksigner.jar sign --ks $PATH_TO_KEYSTORE --ks-key-alias $KEY_ALIAS --ks-pass pass:$KEYSTORE_PASSWORD --key-pass pass:KEY_PASSWORD
````
Is there any success signing your APK manually (without using APK Editor Studio)?

**Comment by Nottt** [comment]
Yes, if I sign with apksigner with `apksigner sign --ks file.keystore` it verifies normally.

**Comment by kefir500** [comment]
Tried different combinations, still cannot reproduce.

Could you please provide the following information:
- JRE version you *verify* against (`Help` --> `About APK Editor Studio` --> `Technologies`).
- JDK version you *sign* against (`javac -version`).
- Type of your key store (JKS, PKCS12…).
- Were you signing the APK via APK Editor Studio (which didn't verify) and signing the APK manually (which did verify) *on the same platform*?

**Comment by Ibuprophen** [comment]
I'm just providing something that may be helpful... 

I've seen similar types of issues that actually result from both 32-bit and 64-bit Java installed together. 

In addition to the above, I've even seen multiple versions/builds installed for one/both of the 32-bit and 64-bit versions as well because the individual doesn't realize that you need to uninstall the older version/build of Java before installing the updated one. 

Just a few things to consider in case you weren't aware of this that's, hopefully, helpful in some way. 

Good Luck! :-) 


~Ibuprophen

**Comment by kefir500** [comment]
Closing this as unconfirmed due to no response from the issuer.
If the issue still persists, please provide the requested information and reopen if needed.
