### ISSUE TITLE
error unpacking apk

### ISSUE THREAD

**Issue by Baka75L** [kefir500/apk-editor-studio#94]
after updating the program, the error "error unpacking apk" appears. reinstalling (both the new version and the previous one) does not help to solve the problem

**Comment by kefir500** [comment]
Could you please share the detailed error message? You can reveal it by clicking the red line.

**Comment by Baka75L** [comment]
oh, sorry, after some manipulations with java, all versions work without errors

**Comment by kefir500** [comment]
I'm glad the issue is resolved 👍
Happy New Year!
