### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#99]
@kefir500 

Please check screenshot.
Red boxes are strings untranslated.
Note: when I ran "Update" for apktool on next run appear the same window (seems update not run).

![APK Editor -1 7 0](https://user-images.githubusercontent.com/1262554/213670914-0aa8dd3a-2833-4a4e-aaab-23fb4fce4196.jpg)

Some untranslated string are in Transiflex repository ("What's new" not).
I didn't receive any notification by Transiflex about new strings to translate.
Now I translated all italian untranslated strings in Transiflex repository.

I checked and in "tools" subfolfer is available apktool v. 2.7.0 but APK editor seems not detect it.

**Comment by bovirus** [comment]
@kefir500 

Thanks. Apktool fixes. As you explained was not a bug of APK Editor.

There was an update on Java machine and environment variable point to old Java version.

**Comment by kefir500** [comment]
Actually, this is an APK Editor Studio bug. We should at least check if Java can be found, and only then notify about available Apktool updates. I've created a dedicated [issue](https://github.com/kefir500/apk-editor-studio/issues/101) since this one targets multiple questions.

**Comment by bovirus** [comment]
@kefir500 

Thanks. 
Please close this issue.

**Comment by kefir500** [comment]
I'll keep it open until I integrate and check the new translations, if you don't mind.

**Comment by kefir500** [comment]
APK Editor Studio v1.7.1 is out.
The Italian translations seem to be fine.
Thanks again, @bovirus!
